### PR TITLE
[Added] travis ci config file and requirements.

### PR DESCRIPTION
**Pull request by SchmidtD**
I added a travis config file.
Additionally I described the requirements within README file.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Thank you very much for contributing! 🤗 Travis seem to fail, can you check that?

**Comment by saschagrunert** [comment]
Thank you!

**Comment by SchmidtD** [comment]
Checked and added missing initial tag.

**Comment by saschagrunert** [comment]
Thank you very much!

**Pull request merged**
